---
number_of_folds: 10
data_fractions: [0.1, 0.5, 1.0, 0.2, 0.3, 0.4, 0.6, 0.7, 0.8, 0.9]


mimic_files:
  - 'CHARTEVENTS'
  - 'INPUTEVENTS_CV'
  - 'INPUTEVENTS_MV'
  - 'ICUSTAYS'
  - 'D_ITEMS'
  - 'D_LABITEMS'
  - 'ADMISSIONS'
  - 'LABEVENTS'
  - 'PATIENTS'
  - 'OUTPUTEVENTS'

datasets:
  original_strats_data:
    split-by-strats: true

  noisy_gaussian_p1.0_m1.0:
    noise-type: 'gaussian'
    noise-p: 1.0
    noise-magnitude: 1.0
    leave-outliers: true
    split-by-strats: true

  noisy_gaussian_p1.0_m2.0:
    noise-type: 'gaussian'
    noise-p: 1.0
    noise-magnitude: 2.0
    leave-outliers: true
    split-by-strats: true

  noisy_gaussian_p1.0_m3.0:
    noise-type: 'gaussian'
    noise-p: 1.0
    noise-magnitude: 3.0
    leave-outliers: true
    split-by-strats: true

  noisy_uniform_p0.25:
    noise-type: 'uniform'
    noise-p: 0.25
    leave-outliers: true
    split-by-strats: true

  noisy_uniform_p0.5:
    noise-type: 'uniform'
    noise-p: 0.5
    leave-outliers: true
    split-by-strats: true

  noisy_uniform_p0.75:
    noise-type: 'uniform'
    noise-p: 0.75
    leave-outliers: true
    split-by-strats: true

  noisy_uniform_p1.0:
    noise-type: 'uniform'
    noise-p: 0.75
    leave-outliers: true
    split-by-strats: true
