metric: &metric val_pr_roc_auc_sum
metric_mode: &metric_mode max

_common_dataset_: &common_dataset
  data_fraction: 1
  max_events: 880
  max_minute: 1440 # 24 * 60
  min_input_minutes: 720 # 12*60
  variables_dropout: 0

train_dataset:
  path: ./src/util/tests/data
  <<: *common_dataset

val_dataset:
  path: ./src/util/tests/data
  <<: *common_dataset

test_dataset:
  path: ./src/util/tests/data
  <<: *common_dataset

trainer:
  max_epochs: 15
  gradient_clip_val: 0.3
  val_check_interval: 0.5


checkpoint_callback:
  monitor: *metric
  mode: *metric_mode
  dirpath: /home/user/.cache/thesis/dev-checkpoints/finetune

early_stop_callback:
  monitor: *metric
  mode: *metric_mode
  patience: 5


train_batch_size: 8
val_batch_size: 8
results_dir: /home/user/.cache/thesis/dev-results

optimizer:
  lr: 5.0e-4
