metric: &metric val_pr_roc_auc_sum
metric_mode: &metric_mode max

_common_dataset_: &common_dataset
  data_fraction: 1
  max_events: 880
  max_minute: 1440 # 24 * 60
  min_input_minutes: 720 # 12*60
  variables_dropout: 0

train_dataset:
  path: /home/user/.cache/thesis/data/preprocessed/train
  <<: *common_dataset

val_dataset:
  path: /home/user/.cache/thesis/data/preprocessed/val
  <<: *common_dataset

test_dataset:
  path: /home/user/.cache/thesis/data/preprocessed/test
  <<: *common_dataset

trainer:
  max_epochs: 60
  gradient_clip_val: 0.3
  val_check_interval: 0.5


checkpoint_callback:
  monitor: *metric
  mode: *metric_mode
  dirpath: /home/user/.cache/thesis/checkpoints/finetune

early_stop_callback:
  monitor: *metric
  mode: *metric_mode
  patience: 15


train_batch_size: 16
val_batch_size: 32
results_dir: /home/user/.cache/thesis/results

optimizer:
  lr: 5.0e-4
