name: thesis_code
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - bioconda::snakemake
  - mamba
  - pipenv
  - pytorch::pytorch==2.4
  - pytorch-cuda=12.1
  - cudnn
